{{- if .Values.passthroughIngress.ipAddressPool }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: passthrough-ingressgateway
  namespace: metallb-system
spec:
  addresses: |-
    {{- range $.Values.passthroughIngress.ipAddressPool }}
    - {{ . }}
    {{- end }}
  serviceAllocation:
    priority: 50
    namespaces:
      - {{ .Values.passthroughIngress.namespace }}
    serviceSelectors:
      - matchLabels:
          {{ .Values.passthroughIngress.matchLabel }}
{{- end }}
