{{- if .Values.ipAddressAdminIngressgateway }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: admin-ingressgateway
  namespace: metallb-system
spec:
  addresses: |-
    {{- range $.Values.adminIngress.ipAddressPool }}
    - {{ . }}/32
    {{- end }}   
  serviceAllocation:
    priority: 50
    namespaces:
      - istio-admin-gateway
    serviceSelectors:
      - matchLabels:
          app: admin-ingressgateway
{{- end }}
