{{- if .Values.tenantIngress.ipAddressPool }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: tenant-ingressgateway
  namespace: metallb-system
spec:
  addresses:
    {{- if not (empty .Values.tenantIngress.ipAddressPool) }}
    {{- if (kindIs "string" .Values.tenantIngress.ipAddressPool) }}
    - {{ .Values.tenantIngress.ipAddressPool }}/32
    {{- else }}
    {{- range .Values.tenantIngress.ipAddressPool }}
    - {{ . }}/32
    {{- end }}
    {{- end }}
    {{- end }}
  serviceAllocation:
    priority: 50
    namespaces:
      - {{ .Values.tenantIngress.namespace }}
    serviceSelectors:
      - matchLabels:
          {{ .Values.tenantIngress.matchLabel }}
{{- end }}
