resources:
  # NOTE: Renovate looks for this exact string to determine when to update the version that is awkwardly stuck in the middle of the file
  # If you change this string, you will break renovate unless you go update the renovate.json5 file.
  - https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml

images:
  - name: quay.io/metallb/controller
    newName: registry1.dso.mil/ironbank/opensource/metallb/controller
    newTag: v0.14.5
  - name: quay.io/metallb/speaker
    newName: registry1.dso.mil/ironbank/opensource/metallb/speaker
    newTag: v0.14.5

patches:
  - target:
      kind: Deployment
      name: controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: controller
      spec:
        template:
          spec:
            securityContext:
              fsGroup: 65532
              runAsNonRoot: true
              runAsUser: 65532
              runAsGroup: 65532
  - target:
      kind: DaemonSet
      name: speaker
    patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: speaker
      spec:
        template:
          spec:
            securityContext:
              fsGroup: 65532
              runAsUser: 0
